### ISSUE TITLE
Ephemeral volume

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/topolvm#75]
## What

Implement [inline ephemeral volume](https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html) for Kubernetes to resolve #41.

Note that ephemeral volume is beta since k8s 1.16.

## How

Matt Martin said he'd like to implement this feature. We'll help you.

https://github.com/cybozu-go/topolvm/issues/75
## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by matthias50** [comment]
@ymmt2005, this seems like a sound approach to this problem. Have you made any progress on this yet? I have some time right now to work on this issue. I was planning on doing some sort of work-around, but this seems like a better solution than what I was contemplating.  I'd rather help this along if I can.  Is there anything I can do to help move this forward?

**Comment by ymmt2005** [comment]
@matthias50 
There is a potential issue to implement this; the current inline volume spec does not allow to specify volume size.  There is a draft KEP to enhance the spec but I think it will take a long time to be approved.
https://github.com/kubernetes/enhancements/pull/1409

Until then, we may use Pod annotations to specify the size.
@satoru-takeuchi Thoughts?

**Comment by matthias50** [comment]
One other question/comment. I noticed that there is this feature to support "local ephemeral storage" as a first class Kubernetes resource: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage.

It almost seems like this would make it possible to just put /var/lib/kubelet on a special partition for the local storage and then let Kubernetes handle the whole thing for you without even needing a CSI driver like topolvm at all.

Have you looked at this approach?

**Comment by ymmt2005** [comment]
That approach seems viable as long as you want an ephemeral filesystem for Pods.
There seem several limitations in local ephemeral storage, though:

- No block device support.
- Pods can be evicted when it overuses the storage.
- It may bother other Pods with `emptyDir` volume because of sharing `/var/lib/kubelet`.

**Comment by matthias50** [comment]
> * It may bother other Pods with `emptyDir` volume because of sharing `/var/lib/kubelet`.

What do yo mean by "bother" here? Do you just mean that they will be sharing disk IOPS or did you have some other concern?

**Comment by ymmt2005** [comment]
My concern is that because `emptyDir` has no size specification, we may not keep enough capacity for them when we consume `/var/lib/kubelet` by using local ephemeral storages.

**Comment by matthias50** [comment]
According to https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage, you can set:

* spec.containers[].resources.limits.ephemeral-storage
* spec.containers[].resources.requests.ephemeral-storage

and that:

"The scheduler ensures that the sum of the resource requests of the scheduled Containers is less than the capacity of the node."

Shouldn't that be enough to guarantee sufficient space is available?

**Comment by matthias50** [comment]
One concern I did find myself. Kubelet implements the space monitoring by periodically scanning emptyDir volume, log directories, and writable layers for their space usage. This means that a pod can temporarily consume more than it's limit (depending on the scan period). K8s supports FS quotas to do the same thing, but only if LocalStorageCapacityIsolationFSQuotaMonitoring is enabled, which is currently an Alpha feature.

**Comment by matthias50** [comment]
> Until then, we may use Pod annotations to specify the size.
> @satoru-takeuchi Thoughts?

Or perhaps, as hinted at by https://github.com/kubernetes/enhancements/pull/1409, we could use some TopoLVM specific volumeAttributes until there is a standard way to do so?

**Comment by matthias50** [comment]
After digging into the code and reading https://github.com/cybozu-go/topolvm/blob/master/docs/design.md. I have another concern. It seems that the actual underlying logical volume gets created as a result of the external-provisioner calling CreateVolume.

By my reading of https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html, when Kubernetes encounters an inline ephemeral volume, it will only send NodePublishVolume and NodeUnpublishVolume. CreateVolume would never get called.  Thus it looks like some large refactor would be required in order to support inline ephemeral volumes because underlying LV creation would need to move from the CreateVolume path to the NodePublishVolume path. 

Did I get this correct?

**Comment by ymmt2005** [comment]
> underlying LV creation would need to move from the CreateVolume path to the NodePublishVolume path.

Yes, it is correct.  But it is easy to distinguish whether `NodePublishVolume` is called for inline volumes or not, so I have no concerns about the implementation other than the volume size matter.

**Comment by matthias50** [comment]
To tack on to my previous comment, it seems like https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190122-csi-inline-volumes.md specifically suggests using the volume attributes to specify size, so we could specify the request something like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
spec:
  containers:
    ...
  volumes:
      - name: vol
        csi:
          driver: topolvm.cybozu.com
          # Passed as NodePublishVolumeRequest.volume_context,
          # valid options depend on the driver.
          volumeAttributes:
              topolvm.cybozu.com/size: 1G
```

**Comment by satoru-takeuchi** [comment]
> @satoru-takeuchi Thoughts?

@matthias50 @ymmt2005

OK, we'll implement it. However, we can't say when it's done for now.

**Comment by matthias50** [comment]
@satoru-takeuchi, @ymmt2005, Thanks. I am willing to take a shot and implementing this and submitting a PR. I started digging through the code and it looks like what should happen is that in node.go, NodePublishVolume should check the volume context to determine if the volume is ephemeral and if so, directly call lvService.CreateLV(). Am I on the right track here?

**Comment by ymmt2005** [comment]
@matthias50 
Yes, right.  We welcome your contributions and will review your PR.
Please make sure that your PR needs to include e2e tests for the added feature.

**Comment by matthias50** [comment]
@ymmt2005, @satoru-takeuchi, I managed to hack something up which seems to handle the NodePublishVolume side. However, I ran into a snag with NodeUnpublishVolume. It turns out that the volume context doesn't get passed along to NodeUnpublishVolume, so there isn't a great built-in way to determine if the volume is an inline ephemeral volume or not in the context of NodeUnpublishVolume. We need to know this in order to determine if RemoveLV() needs to be called on the volume in NodeUnpublishVolume.

I don't see a great way out of this other than to rely on naming conventions for the volumes. I noticed that the inline ephemeral volumes end up with a volume_id like: csi-0070a9a4cc3fc5b46789ba0aa752c1ac2948cdf12d5d50403f6a77c6d657a5ec whereas the existing volumes get names like 0906d6e0-bd83-45ed-b5af-7baa574f4124, so looking for a volume_id csi-prefix is a way to determine if NodeUnpublishVolume should call RemoveLV() or not. 

This seems like a rather indirect and perhaps brittle way to determine when the LV should be removed. Do you have any other ideas?

**Comment by matthias50** [comment]
Another wrinkle is that it looks like mutate_pod.go needs to be updated to account for adding the resource requests/limits when there is an inline ephemeral volume. The current code only catches when there is a volume claim with the pod.

**Comment by satoru-takeuchi** [comment]
@matthias50 

> I don't see a great way out of this other than to rely on naming conventions for the volumes. I noticed that the inline ephemeral volumes end up with a volume_id like: csi-0070a9a4cc3fc5b46789ba0aa752c1ac2948cdf12d5d50403f6a77c6d657a5ec whereas the existing volumes get names like 0906d6e0-bd83-45ed-b5af-7baa574f4124, so looking for a volume_id csi-prefix is a way to determine if NodeUnpublishVolume should call RemoveLV() or not.

Since there is no guarantee that the volume id with "csi-" prefix means only ephemeral volume, I hesitate to use this way.

How about the following way?

- Add `Ephemeral bool` filed  in the `LogicalVolumeStatus` for each volume.
  https://github.com/cybozu-go/topolvm/blob/master/api/v1/logicalvolume_types.go#L22
- Set `Ephemeral` to `true` when `NodePublishVolume()` is called for ephemeral volume.
- When calling `NodeUnpublishVolume()`, get LogicalVolumeStatus from ID with `findVolumeByID().Status`.

It's same way as hostPath driver.
https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/nodeserver.go#L227

> Another wrinkle is that it looks like mutate_pod.go needs to be updated to account for adding the resource requests/limits when there is an inline ephemeral volume. The current code only catches when there is a volume claim with the pod.

I think so too.

**Comment by matthias50** [comment]
> * Add `Ephemeral bool` filed  in the `LogicalVolumeStatus` for each volume.
>   https://github.com/cybozu-go/topolvm/blob/master/api/v1/logicalvolume_types.go#L22
> * Set `Ephemeral` to `true` when `NodePublishVolume()` is called for ephemeral volume.
> * When calling `NodeUnpublishVolume()`, get LogicalVolumeStatus from ID with `findVolumeByID().Status`.

Thanks for the suggestion. That way seems much better. I'll try that.

**Comment by matthias50** [comment]
@satoru-takeuchi , I tried going down the path of storing LogicalVolumeStatus and, as I mentioned on slack, it appears that the hostPath driver is storing the volume metadata in RAM which seems like a bad idea. See https://github.com/kubernetes-csi/csi-driver-host-path/blob/9fdddc2061b9013286e01189b2bf3268276af99b/pkg/hostpath/hostpath.go#L138 and there doesn't seem to be anywhere we could store this volume metadata persistently in Kubernetes.

As a variant of the volume_id approach, I propose we instead prepend a set string, say "topolvm-ephemeral" to the raw volume id in https://github.com/cybozu-go/topolvm/blob/3cf92fe3de9c2db7742b831d00ec4f5400042a02/driver/node.go#L58 if it is an ephemeral volume. Then in ```NodeUnplublishVolume()``` we can determine if the volume is ephemeral by searching for the existence of an LV with the name "topolvm-ephemeral-<volume_name>". Concretely, the name would something like this: topolvm-ephemeral-csi-b6773f29044e75e283a95acf702cee2f8742b7e7458ce26984382372948846fe. If a volume exists with this prefix, then we know the request is to unpublished an ephemeral local volume. If such a volume doesn't exist, then we know the request is for a "normal" volume.

Since we would be controlling the prefix, this seems like a safe approach when compared to my earlier suggestion of relying on the "csi-" prefix. Also, it seems better than the hostPath approach which seems to not work correctly if the CSI node level pod resets after a volume is created and before it is deleted.

Thoughts?

**Comment by satoru-takeuchi** [comment]
@matthias50 

> it appears that the hostPath driver is storing the volume metadata in RAM which seems like a bad idea.

Yes.

> As a variant of the volume_id approach, I propose we instead prepend a set string, say topolvm-ephemeral- to the raw volume id

I see. In addition, there are other ways to store whether a volume is ephemeral or not persistently. We can store this information in CRD (it's stored in etcd), LVM tag, and filesystem, and so on.

I'll think of which is the proper way. Please wait for a while.

**Comment by satoru-takeuchi** [comment]
@matthias50 I consider LVM tag is the proper way. It's because of the following reasons.

- volume_id approach seems a bit hacky. I hesitate to embed volume attributes like whether ephemeral volume or not, in volume name. I'd like to store there attributes in the dedicated place as possible.
- Adding new field to LogicalVolume CRD changes its definition. The document describes the purpose of this CRD is to help communication between CSI controller and node services. However, ephemeral volume is not related to controller.
- Creating new CRD seems to be overkill
- LVM tag is better than filesystem since it directly corresponds to each volume.

**Comment by matthias50** [comment]
@satoru-takeuchi, thanks for the feedback. I agree that LVM tags seem like a better approach than using names of the volumes. I'll work on implementing this.

**Comment by matthias50** [comment]
I have a question regarding the yaml files which get applied to the cluster and e2e tests for the various Kubernetes versions. In order to make this work, the CSI driver spec needs to be modified to as follows (both for CI clusters and for "real" clusters")

```
   name: topolvm.cybozu.com
 spec:
   attachRequired: true
+  podInfoOnMount: true
+  volumeLifecycleModes:
+    - Persistent
+    - Ephemeral
```

volumeLifecycleModes is a new field for K8s 1.16, so these changes can't be applied to the 1.14 and 1.15 clusters still supported by topolvm.

Similarly, as noted in the description, inline ephemeral volume is new for 1.16 so any e2e tests for this should only run on 1.16 or greater.

I didn't see any analogues in the code for this where the deployment or tests vary based on the k8s version. @satoru-takeuchi , @ymmt2005, can you suggest how this should be handled?

**Comment by matthias50** [comment]
> I didn't see any analogues in the code for this where the tests vary based on the k8s version.

For this, I'm going to try to leverage ginkgo's ```--skip=REGEXP``` https://onsi.github.io/ginkgo/ and pass an exclusion regex when 1.14 or 1.15 is specified for ```TEST_KUBERNETES_VERSION``` in the e2e Makefile.

For the CSI driver spec, in the e2e tests, I'll look at using the Makefile to make sure that the yaml manifests applied to the kind cluster vary based on ```TEST_KUBERNETES_VERSION```. 

Not sure what do do about this yet: https://github.com/cybozu-go/topolvm/blob/a2f3231d5a77f210731ab62d89d7a50a1d590ed0/deploy/manifests/controller.yaml#L7. The deployment manifests are static, so I don't know how to have these vary based on what Kubernetes version people are using.

**Comment by ymmt2005** [comment]
@matthias50 
Probably, we can use `kustomize`'s override feature for each Kubernetes version.
Do you know how to use `kustomize`?

**Comment by ymmt2005** [comment]
An example of overriding manifests under `deploy` is [`example/kustomization.yaml`](https://github.com/cybozu-go/topolvm/blob/master/example/kustomization.yaml).

The file patches the original manifests with strategic merge patches such as [`example/controller.yaml`](https://github.com/cybozu-go/topolvm/blob/master/example/controller.yaml).

You can patch `CSIDriver` in `controller.yaml` just the same way.

**Comment by matthias50** [comment]
> @matthias50
> Probably, we can use `kustomize`'s override feature for each Kubernetes version.
> Do you know how to use `kustomize`?

I'm familiar with ```kustomize``` as I've used it to develop some of our deployments. With your suggestion are you taking about the e2e case or the real deployment? For the e2e, given that it is driven by a Makefile, there are all sorts of ways to solve the problem. For the "real" deployment, from what I can tell the deployment assumes just using raw ```kubectl```, not ```kustomize```, so I wasn't sure how to bring that in.

**Comment by ymmt2005** [comment]
Since Kubernetes 1.14, `kubectl apply -k` works the same as `kustomize`.
I think we can update the deploy guide to use `kubectl apply -k` to apply patched manifests for the target Kubernetes version.

**Comment by ymmt2005** [comment]
Ah, in fact, `kubectl kustomize` is just an embedded version of `kustomize`.

**Comment by matthias50** [comment]
> Ah, in fact, `kubectl kustomize` is just an embedded version of `kustomize`.

*Mostly* this is the case. However, I found that the "full" ```kustomize``` does have some command line options which aren't supported by the ```kustomize``` embedded in ```kubectl```. One example is support for ```--load_restrictor='none'```.  Hopefully we won't need such esoteric things for TopoLVM (which I did in fact need for my use case). I'll try this out for the deployment and see how it works.
